name: Checking models on huggingface
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: 42 16 1 * *
  workflow_dispatch:

env:
  PROCESS_COUNT: 8
jobs:
  automatic-updates:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    defaults:
        run:
          working-directory: ./gallery-scrapers/huggingface
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install virtualenv
        run: pip install virtualenv
  
      - name: Create virtual environment
        run: python -m venv venv
  
      - name: Activate the virtual environment
        run: source venv/bin/activate
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Launch Scraper
        working-directory: .
        run: python ./gallery-scrapers/huggingface/main.py --count $PROCESS_COUNT

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
